<?php
$replace[]=['find'=>'API', 'replace'=>'API'];
$replace[]=['find'=>'API!key', 'replace'=>'API!chiave'];
$replace[]=['find'=>'BY-SA', 'replace'=>'BY-SA'];
$replace[]=['find'=>'BeautifulSoup', 'replace'=>'BeautifulSoup'];
$replace[]=['find'=>'CC-BY-SA', 'replace'=>'CC-BY-SA'];
$replace[]=['find'=>'CC-BY-SA', 'replace'=>'CC-BY-SA'];
$replace[]=['find'=>'Creative Commons License', 'replace'=>'Licenza Creative Commons'];
$replace[]=['find'=>'DSU pattern', 'replace'=>'DSU pattern'];
$replace[]=['find'=>'ElementTree', 'replace'=>'ElementTree'];
$replace[]=['find'=>'ElementTree!find', 'replace'=>'ElementTree!find'];
$replace[]=['find'=>'ElementTree!findall', 'replace'=>'ElementTree!findall'];
$replace[]=['find'=>'ElementTree!fromstring', 'replace'=>'ElementTree!fromstring'];
$replace[]=['find'=>'ElementTree!get', 'replace'=>'ElementTree!get'];
$replace[]=['find'=>'False special value', 'replace'=>'False special value'];
$replace[]=['find'=>'Free Documentation License, GNU', 'replace'=>'Free Documentation License, GNU'];
$replace[]=['find'=>'GNU Free Documentation License', 'replace'=>'GNU Free Documentation License'];
$replace[]=['find'=>'Google', 'replace'=>'Google'];
$replace[]=['find'=>'Google!map', 'replace'=>'Google!mappa'];
$replace[]=['find'=>'Google!page rank', 'replace'=>'Google!page rank'];
$replace[]=['find'=>'HTML', 'replace'=>'HTML'];
$replace[]=['find'=>'IOError', 'replace'=>'IOError'];
$replace[]=['find'=>'IndexError', 'replace'=>'IndexError'];
$replace[]=['find'=>'JSON', 'replace'=>'JSON'];
$replace[]=['find'=>'JavaScript Object Notation', 'replace'=>'JavaScript Object Notation'];
$replace[]=['find'=>'KeyError', 'replace'=>'KeyError'];
$replace[]=['find'=>'None special value', 'replace'=>'Valore speciale!None'];
$replace[]=['find'=>'OAuth', 'replace'=>'OAuth'];
$replace[]=['find'=>'PEMDAS', 'replace'=>'PEMDAS'];
$replace[]=['find'=>'Python 2.0', 'replace'=>'Python 2.0'];
$replace[]=['find'=>'Python 3.0', 'replace'=>'Python 3.0'];
$replace[]=['find'=>'Pythonic', 'replace'=>'Pythonico'];
$replace[]=['find'=>'QA', 'replace'=>'QA'];
$replace[]=['find'=>'Quality Assurance', 'replace'=>'Controllo Qualità'];
$replace[]=['find'=>'Romeo and Juliet', 'replace'=>'Romeo e Giulietta'];
$replace[]=['find'=>'SOA', 'replace'=>'SOA'];
$replace[]=['find'=>'Service Oriented Architecture', 'replace'=>'Service Oriented Architecture'];
$replace[]=['find'=>'True special value', 'replace'=>'Valore speciale!True'];
$replace[]=['find'=>'TypeError', 'replace'=>'TypeError'];
$replace[]=['find'=>'Unicode', 'replace'=>'Unicode'];
$replace[]=['find'=>'ValueError', 'replace'=>'ValueError'];
$replace[]=['find'=>'Visualization!map', 'replace'=>'Visualizzazione!mappa'];
$replace[]=['find'=>'Visualization!networks', 'replace'=>'Visualizzazione!reti'];
$replace[]=['find'=>'Visualization!page rank', 'replace'=>'Visualizzazione!rank della pagina'];
$replace[]=['find'=>'XML', 'replace'=>'XML'];
$replace[]=['find'=>'access', 'replace'=>'accesso'];
$replace[]=['find'=>'accumulator', 'replace'=>'accumulatore'];
$replace[]=['find'=>'accumulator!sum', 'replace'=>'accumulatore!sum'];
$replace[]=['find'=>'algorithm', 'replace'=>'algoritmo'];
$replace[]=['find'=>'aliasing', 'replace'=>'aliasing'];
$replace[]=['find'=>'aliasing!copying to avoid', 'replace'=>'aliasing!copiare per evitare'];
$replace[]=['find'=>'alternative execution', 'replace'=>'esecuzione alternativa'];
$replace[]=['find'=>'analizzare', 'replace'=>'analizzare'];
$replace[]=['find'=>'and operator', 'replace'=>'operatore AND'];
$replace[]=['find'=>'append method', 'replace'=>'metodo append'];
$replace[]=['find'=>'argument', 'replace'=>'argomento'];
$replace[]=['find'=>'argument!keyword', 'replace'=>'argomento!parola chiave'];
$replace[]=['find'=>'argument!list', 'replace'=>'argomento!elenco'];
$replace[]=['find'=>'argument!optional', 'replace'=>'argomento!opzionale'];
$replace[]=['find'=>'arithmetic operator', 'replace'=>'operatore artimetico'];
$replace[]=['find'=>'assignment', 'replace'=>'assegnazione'];
$replace[]=['find'=>'assignment statement', 'replace'=>'istruzione assegnazione'];
$replace[]=['find'=>'assignment!item', 'replace'=>'assegnazione!item'];
$replace[]=['find'=>'assignment!tuple', 'replace'=>'assegnazione!tupla'];
$replace[]=['find'=>'attribute', 'replace'=>'attributo'];
$replace[]=['find'=>'binary file', 'replace'=>'file binario'];
$replace[]=['find'=>'bisection, debugging by', 'replace'=>'bisezione, debugging per'];
$replace[]=['find'=>'body', 'replace'=>'body'];
$replace[]=['find'=>'bool type', 'replace'=>'tipo bool'];
$replace[]=['find'=>'boolean expression', 'replace'=>'espressione booleana'];
$replace[]=['find'=>'boolean operator', 'replace'=>'operatore booleano'];
$replace[]=['find'=>'bracket operator', 'replace'=>'operatore parentesi'];
$replace[]=['find'=>'bracket!squiggly', 'replace'=>'parentesi ondulata'];
$replace[]=['find'=>'branch', 'replace'=>'ramo'];
$replace[]=['find'=>'break statement', 'replace'=>'istruzione!break'];
$replace[]=['find'=>'bug', 'replace'=>'bug'];
$replace[]=['find'=>'cache', 'replace'=>'cache'];
$replace[]=['find'=>'case-sensitivity, variable names', 'replace'=>'case-sensitivity, nomi delle variabili'];
$replace[]=['find'=>'catch', 'replace'=>'catch'];
$replace[]=['find'=>'celsius', 'replace'=>'celsius'];
$replace[]=['find'=>'central processing unit', 'replace'=>'Unità Centrale di Elaborazione'];
$replace[]=['find'=>'chained conditional', 'replace'=>'catene condizionali'];
$replace[]=['find'=>'character', 'replace'=>'carattere'];
$replace[]=['find'=>'child class', 'replace'=>'classe figlia'];
$replace[]=['find'=>'choice function', 'replace'=>'funzione!choice'];
$replace[]=['find'=>'class', 'replace'=>'classe'];
$replace[]=['find'=>'class keyword', 'replace'=>'keyword!class'];
$replace[]=['find'=>'class!float', 'replace'=>'classe!float'];
$replace[]=['find'=>'class!int', 'replace'=>'classe!int'];
$replace[]=['find'=>'class!str', 'replace'=>'classe!str'];
$replace[]=['find'=>'close method', 'replace'=>'metodo close'];
$replace[]=['find'=>'codice macchina', 'replace'=>'codice macchina'];
$replace[]=['find'=>'codice sorgente', 'replace'=>'codice sorgente'];
$replace[]=['find'=>'collaboratori', 'replace'=>'collaboratori'];
$replace[]=['find'=>'colon', 'replace'=>'virgola'];
$replace[]=['find'=>'comment', 'replace'=>'commento'];
$replace[]=['find'=>'comparable', 'replace'=>'comparabile'];
$replace[]=['find'=>'comparison operator', 'replace'=>'operatore di comparazione'];
$replace[]=['find'=>'comparison!string', 'replace'=>'comparazione!stringa'];
$replace[]=['find'=>'comparison!tuple', 'replace'=>'comparazione!tupla'];
$replace[]=['find'=>'compilare', 'replace'=>'compilare'];
$replace[]=['find'=>'composition', 'replace'=>'composizione'];
$replace[]=['find'=>'compound statement', 'replace'=>'istruzioni composte'];
$replace[]=['find'=>'concatenation', 'replace'=>'concatenazione'];
$replace[]=['find'=>'concatenation!list', 'replace'=>'concatezione!list'];
$replace[]=['find'=>'condition', 'replace'=>'condizione'];
$replace[]=['find'=>'conditional executions', 'replace'=>'esecuzione condizionale'];
$replace[]=['find'=>'conditional statement', 'replace'=>'istruzione condizionale'];
$replace[]=['find'=>'conditional!chained', 'replace'=>'condizioni!catena'];
$replace[]=['find'=>'conditional!nested', 'replace'=>'condizioni!annidamento'];
$replace[]=['find'=>'connect function', 'replace'=>'funzione connect'];
$replace[]=['find'=>'consistency check', 'replace'=>'controllo della consistenza'];
$replace[]=['find'=>'constraint', 'replace'=>'vincolo'];
$replace[]=['find'=>'construct', 'replace'=>'construct'];
$replace[]=['find'=>'constructor', 'replace'=>'costruttore'];
$replace[]=['find'=>'continue statement', 'replace'=>'istruzione continue'];
$replace[]=['find'=>'conversion!type', 'replace'=>'conversione!tipo'];
$replace[]=['find'=>'copy!slice', 'replace'=>'copia!slice'];
$replace[]=['find'=>'copy!to avoid aliasing', 'replace'=>'copia!per evitare aliasing'];
$replace[]=['find'=>'count method', 'replace'=>'metodo count'];
$replace[]=['find'=>'counter', 'replace'=>'contatore'];
$replace[]=['find'=>'counting and looping', 'replace'=>'conteggio e loop'];
$replace[]=['find'=>'curl', 'replace'=>'curl'];
$replace[]=['find'=>'cursor', 'replace'=>'cursore'];
$replace[]=['find'=>'cursor function', 'replace'=>'funzione cursor'];
$replace[]=['find'=>'data structure', 'replace'=>'struttura dei dati'];
$replace[]=['find'=>'database', 'replace'=>'database'];
$replace[]=['find'=>'database browser', 'replace'=>'database browser'];
$replace[]=['find'=>'database normalization', 'replace'=>'normalizzazione database'];
$replace[]=['find'=>'database!indexes', 'replace'=>'database!indici'];
$replace[]=['find'=>'debugging', 'replace'=>'debugging'];
$replace[]=['find'=>'debugging!by bisection', 'replace'=>'debugging!per bisezione'];
$replace[]=['find'=>'decorate-sort-undecorate pattern', 'replace'=>'decorate-sort-undecorate pattern'];
$replace[]=['find'=>'decrement', 'replace'=>'decrement'];
$replace[]=['find'=>'def keyword', 'replace'=>'parola chiave def'];
$replace[]=['find'=>'definition!function', 'replace'=>'definizione!funzione'];
$replace[]=['find'=>'del operator', 'replace'=>'operatore del'];
$replace[]=['find'=>'deletion, element of list', 'replace'=>'cancellare, elemento di una lista'];
$replace[]=['find'=>'delimiter', 'replace'=>'delimitatore'];
$replace[]=['find'=>'destructor', 'replace'=>'destructor'];
$replace[]=['find'=>'deterministic', 'replace'=>'deterministico'];
$replace[]=['find'=>'development plan!random walk programming', 'replace'=>'development plan!random walk programming'];
$replace[]=['find'=>'dict function', 'replace'=>'funzione dict'];
$replace[]=['find'=>'dictionary', 'replace'=>'dizionario'];
$replace[]=['find'=>'dictionary!looping with', 'replace'=>'dictionary!looping con'];
$replace[]=['find'=>'dictionary!traversal', 'replace'=>'dictionary!attraversamento'];
$replace[]=['find'=>'dir', 'replace'=>'dir'];
$replace[]=['find'=>'divisibility', 'replace'=>'divisibilità'];
$replace[]=['find'=>'division!floating-point', 'replace'=>'divisione!floating-point'];
$replace[]=['find'=>'dot notation', 'replace'=>'notazione puntata'];
$replace[]=['find'=>'eXtensible Markup Language', 'replace'=>'eXtensible Markup Language'];
$replace[]=['find'=>'element', 'replace'=>'elemento'];
$replace[]=['find'=>'element deletion', 'replace'=>'cancellazione elemento'];
$replace[]=['find'=>'elif keyword', 'replace'=>'parola chiave alif'];
$replace[]=['find'=>'ellipses', 'replace'=>'elisione'];
$replace[]=['find'=>'else keyword', 'replace'=>'parola chiave else'];
$replace[]=['find'=>'email address', 'replace'=>'indirizzo email'];
$replace[]=['find'=>'empty list', 'replace'=>'elenco vuoto'];
$replace[]=['find'=>'empty string', 'replace'=>'stringa vuota'];
$replace[]=['find'=>'encapsulation', 'replace'=>'incapsulamento'];
$replace[]=['find'=>'end of line character', 'replace'=>'carattere a capo'];
$replace[]=['find'=>'equivalence', 'replace'=>'equivalenza'];
$replace[]=['find'=>'equivalent', 'replace'=>'equivalente'];
$replace[]=['find'=>'error message', 'replace'=>'messaggio d\'errore'];
$replace[]=['find'=>'error!runtime', 'replace'=>'errore!runtime'];
$replace[]=['find'=>'error!semantic', 'replace'=>'errore!semantico'];
$replace[]=['find'=>'error!shape', 'replace'=>'error!shape'];
$replace[]=['find'=>'error!syntax', 'replace'=>'errore!sintassi'];
$replace[]=['find'=>'errore semantico', 'replace'=>'errore semantico'];
$replace[]=['find'=>'evaluate', 'replace'=>'valutazione'];
$replace[]=['find'=>'exception', 'replace'=>'eccezione'];
$replace[]=['find'=>'exception!IOError', 'replace'=>'eccezione!IOError'];
$replace[]=['find'=>'exception!IndexError', 'replace'=>'eccezione!IndexError'];
$replace[]=['find'=>'exception!KeyError', 'replace'=>'eccezione!KeyError'];
$replace[]=['find'=>'exception!TypeError', 'replace'=>'eccezione!TypeError'];
$replace[]=['find'=>'exception!ValueError', 'replace'=>'eccezione!ValueError'];
$replace[]=['find'=>'experimental debugging', 'replace'=>'debugging sperimentale'];
$replace[]=['find'=>'expression', 'replace'=>'espressione'];
$replace[]=['find'=>'expression!boolean', 'replace'=>'expressione!booleana'];
$replace[]=['find'=>'extend method', 'replace'=>'metodo extend'];
$replace[]=['find'=>'fahrenheit', 'replace'=>'fahrenheit'];
$replace[]=['find'=>'file', 'replace'=>'file'];
$replace[]=['find'=>'file handle', 'replace'=>'gestore file'];
$replace[]=['find'=>'file!open', 'replace'=>'file!apertura'];
$replace[]=['find'=>'file!reading', 'replace'=>'file!lettura'];
$replace[]=['find'=>'file!writing', 'replace'=>'file!scrittura'];
$replace[]=['find'=>'filter pattern', 'replace'=>'pattern filter'];
$replace[]=['find'=>'findall', 'replace'=>'findall'];
$replace[]=['find'=>'flag', 'replace'=>'flag'];
$replace[]=['find'=>'float function', 'replace'=>'funzione float'];
$replace[]=['find'=>'float type', 'replace'=>'tipo float'];
$replace[]=['find'=>'floating-point', 'replace'=>'virgola mobile'];
$replace[]=['find'=>'floating-point division', 'replace'=>'divisione a virgola mobile'];
$replace[]=['find'=>'flow control', 'replace'=>'controllo di flusso'];
$replace[]=['find'=>'flow of execution', 'replace'=>'flusso di esecuzione'];
$replace[]=['find'=>'for loop', 'replace'=>'ciclo for'];
$replace[]=['find'=>'for statement', 'replace'=>'istruzione for'];
$replace[]=['find'=>'foreign key', 'replace'=>'chiave esterna'];
$replace[]=['find'=>'format operator', 'replace'=>'operatore format'];
$replace[]=['find'=>'format sequence', 'replace'=>'sequenza di formato'];
$replace[]=['find'=>'format string', 'replace'=>'formato stringa'];
$replace[]=['find'=>'frequency', 'replace'=>'frequenza'];
$replace[]=['find'=>'frequency!letter', 'replace'=>'frequenza!lettera'];
$replace[]=['find'=>'fruitful function', 'replace'=>'funzione fruttuosa'];
$replace[]=['find'=>'function', 'replace'=>'funzione'];
$replace[]=['find'=>'function argument', 'replace'=>'argomento di funzione'];
$replace[]=['find'=>'function call', 'replace'=>'chiamata di una funzione'];
$replace[]=['find'=>'function definition', 'replace'=>'definizione di una funzione'];
$replace[]=['find'=>'function object', 'replace'=>'oggetto di una funzione'];
$replace[]=['find'=>'function parameter', 'replace'=>'parametri di una funzione'];
$replace[]=['find'=>'function!choice', 'replace'=>'funzione!choice'];
$replace[]=['find'=>'function!connect', 'replace'=>'funzione!connect'];
$replace[]=['find'=>'function!cursor', 'replace'=>'funzione!cursor'];
$replace[]=['find'=>'function!dict', 'replace'=>'funzione!dict'];
$replace[]=['find'=>'function!float', 'replace'=>'funzione!float'];
$replace[]=['find'=>'function!int', 'replace'=>'funzione!int'];
$replace[]=['find'=>'function!len', 'replace'=>'funzione!len'];
$replace[]=['find'=>'function!list', 'replace'=>'funzione!list'];
$replace[]=['find'=>'function!log', 'replace'=>'funzione!log'];
$replace[]=['find'=>'function!open', 'replace'=>'funzione!open'];
$replace[]=['find'=>'function!randint', 'replace'=>'funzione!randint'];
$replace[]=['find'=>'function!random', 'replace'=>'funzione!random'];
$replace[]=['find'=>'function!repr', 'replace'=>'funzione!repr'];
$replace[]=['find'=>'function!reversed', 'replace'=>'funzione!reversed'];
$replace[]=['find'=>'function!sorted', 'replace'=>'funzione!sorted'];
$replace[]=['find'=>'function!sqrt', 'replace'=>'funzione!sqrt'];
$replace[]=['find'=>'function!str', 'replace'=>'funzione!str'];
$replace[]=['find'=>'function!tuple', 'replace'=>'funzione!tuple'];
$replace[]=['find'=>'function, fruitful', 'replace'=>'funzione, fruttuosa'];
$replace[]=['find'=>'function, math', 'replace'=>'funzione!math'];
$replace[]=['find'=>'function, reasons for', 'replace'=>'funzione, ragioni per una'];
$replace[]=['find'=>'function, trigonometric', 'replace'=>'funzione, trigonometrica'];
$replace[]=['find'=>'function, void', 'replace'=>'funzione, void'];
$replace[]=['find'=>'funzione di stampa', 'replace'=>'funzione di stampa'];
$replace[]=['find'=>'funzione!stampa', 'replace'=>'funzione!stampa'];
$replace[]=['find'=>'gather', 'replace'=>'raccogliere'];
$replace[]=['find'=>'geocoding', 'replace'=>'geocoding'];
$replace[]=['find'=>'get method', 'replace'=>'metodo get'];
$replace[]=['find'=>'greedy', 'replace'=>'avido'];
$replace[]=['find'=>'greedy matching', 'replace'=>'abbinamento avido'];
$replace[]=['find'=>'grep', 'replace'=>'grep'];
$replace[]=['find'=>'guardian pattern', 'replace'=>'pattern del guardiano'];
$replace[]=['find'=>'hardware', 'replace'=>'hardware'];
$replace[]=['find'=>'hardware!architettura', 'replace'=>'hardware!architettura'];
$replace[]=['find'=>'hash function', 'replace'=>'funzione hash'];
$replace[]=['find'=>'hash table', 'replace'=>'tabella hash'];
$replace[]=['find'=>'hashable', 'replace'=>'hashable'];
$replace[]=['find'=>'hashtable', 'replace'=>'tabella hash'];
$replace[]=['find'=>'header', 'replace'=>'intestazione'];
$replace[]=['find'=>'histogram', 'replace'=>'istogramma'];
$replace[]=['find'=>'identical', 'replace'=>'identico'];
$replace[]=['find'=>'identity', 'replace'=>'identità'];
$replace[]=['find'=>'idiom', 'replace'=>'idioma'];
$replace[]=['find'=>'if statement', 'replace'=>'istruzione if'];
$replace[]=['find'=>'image!jpg', 'replace'=>'immagine!jpg'];
$replace[]=['find'=>'immutability', 'replace'=>'immutabile'];
$replace[]=['find'=>'implementation', 'replace'=>'implementazione'];
$replace[]=['find'=>'import statement', 'replace'=>'istruzione import'];
$replace[]=['find'=>'in operator', 'replace'=>'operatore in'];
$replace[]=['find'=>'increment', 'replace'=>'incremento'];
$replace[]=['find'=>'indentation', 'replace'=>'indentazione'];
$replace[]=['find'=>'index', 'replace'=>'indice'];
$replace[]=['find'=>'index!looping with', 'replace'=>'indice!looping con'];
$replace[]=['find'=>'index!negative', 'replace'=>'indice!negativo'];
$replace[]=['find'=>'index!slice', 'replace'=>'indice!divisione'];
$replace[]=['find'=>'index!starting at zero', 'replace'=>'indice!partenza da zero'];
$replace[]=['find'=>'infinite loop', 'replace'=>'ciclo infinito'];
$replace[]=['find'=>'inheritance', 'replace'=>'ereditarietà'];
$replace[]=['find'=>'initialization (before update)', 'replace'=>'inizializzazione (prima dell\'aggiornamento)'];
$replace[]=['find'=>'instance', 'replace'=>'istanza'];
$replace[]=['find'=>'int function', 'replace'=>'funzione int'];
$replace[]=['find'=>'int type', 'replace'=>'tipo int'];
$replace[]=['find'=>'integer', 'replace'=>'intero'];
$replace[]=['find'=>'interactive mode', 'replace'=>'modalità interativa'];
$replace[]=['find'=>'interprete', 'replace'=>'interprete'];
$replace[]=['find'=>'invocation', 'replace'=>'invocazione'];
$replace[]=['find'=>'is operator', 'replace'=>'operatore is'];
$replace[]=['find'=>'item', 'replace'=>'item'];
$replace[]=['find'=>'item assignment', 'replace'=>'assegnazione di un item'];
$replace[]=['find'=>'item update', 'replace'=>'aggiornamento di un item'];
$replace[]=['find'=>'item!dictionary', 'replace'=>'item!dizionario'];
$replace[]=['find'=>'items method', 'replace'=>'metodo items'];
$replace[]=['find'=>'iteration', 'replace'=>'iterazione'];
$replace[]=['find'=>'join method', 'replace'=>'metodo join'];
$replace[]=['find'=>'jpg', 'replace'=>'jpg'];
$replace[]=['find'=>'key', 'replace'=>'chiave'];
$replace[]=['find'=>'key-value pair', 'replace'=>'coppia chiave-valore'];
$replace[]=['find'=>'keyboard input', 'replace'=>'input da tastiera'];
$replace[]=['find'=>'keys method', 'replace'=>'metodo keys'];
$replace[]=['find'=>'keyword', 'replace'=>'parola chiave'];
$replace[]=['find'=>'keyword argument', 'replace'=>'parola chiave argument'];
$replace[]=['find'=>'keyword!def', 'replace'=>'parola chiave!def'];
$replace[]=['find'=>'keyword!elif', 'replace'=>'parola chiave!elif'];
$replace[]=['find'=>'keyword!else', 'replace'=>'parola chiave!else'];
$replace[]=['find'=>'len function', 'replace'=>'funzione len'];
$replace[]=['find'=>'letter frequency', 'replace'=>'frequenza della lettera'];
$replace[]=['find'=>'linguaggio di alto livello', 'replace'=>'linguaggio di alto livello'];
$replace[]=['find'=>'linguaggio di basso livello', 'replace'=>'linguaggio di basso livello'];
$replace[]=['find'=>'linguaggio di programmazione', 'replace'=>'linguaggio di programmazione'];
$replace[]=['find'=>'linguaggio!programmazione', 'replace'=>'linguaggio!programmazione'];
$replace[]=['find'=>'list', 'replace'=>'elenco'];
$replace[]=['find'=>'list object', 'replace'=>'oggetto elenco'];
$replace[]=['find'=>'list!as argument', 'replace'=>'elenco!come argomento'];
$replace[]=['find'=>'list!concatenation', 'replace'=>'elenco!concantenazione'];
$replace[]=['find'=>'list!copy', 'replace'=>'elenco!copia'];
$replace[]=['find'=>'list!element', 'replace'=>'elenco!elemento'];
$replace[]=['find'=>'list!empty', 'replace'=>'elenco!vuoto'];
$replace[]=['find'=>'list!function', 'replace'=>'elenco!funzione'];
$replace[]=['find'=>'list!index', 'replace'=>'elenco!indice'];
$replace[]=['find'=>'list!membership', 'replace'=>'elenco!membership'];
$replace[]=['find'=>'list!method', 'replace'=>'elenco!metodo'];
$replace[]=['find'=>'list!nested', 'replace'=>'elenco!inestata'];
$replace[]=['find'=>'list!operation', 'replace'=>'elenco!operazione'];
$replace[]=['find'=>'list!repetition', 'replace'=>'elenco!ripetizione'];
$replace[]=['find'=>'list!slice', 'replace'=>'elenco!slice'];
$replace[]=['find'=>'list!traversal', 'replace'=>'elenco!traversal'];
$replace[]=['find'=>'log function', 'replace'=>'funzione log'];
$replace[]=['find'=>'logical key', 'replace'=>'chiave logica'];
$replace[]=['find'=>'logical operator', 'replace'=>'operatore logico'];
$replace[]=['find'=>'lookup', 'replace'=>'ricerca'];
$replace[]=['find'=>'loop', 'replace'=>'ciclo'];
$replace[]=['find'=>'loop!for', 'replace'=>'ciclo!for'];
$replace[]=['find'=>'loop!infinite', 'replace'=>'ciclo!infinito'];
$replace[]=['find'=>'loop!maximum', 'replace'=>'ciclo!massimo'];
$replace[]=['find'=>'loop!minimum', 'replace'=>'ciclo!minimo'];
$replace[]=['find'=>'loop!nested', 'replace'=>'ciclo!inestato'];
$replace[]=['find'=>'loop!traversal', 'replace'=>'ciclo!trasversale'];
$replace[]=['find'=>'loop!while', 'replace'=>'ciclo!while'];
$replace[]=['find'=>'looping and counting', 'replace'=>'cicli e conteggi'];
$replace[]=['find'=>'looping!with dictionaries', 'replace'=>'ciclo!con dizionari'];
$replace[]=['find'=>'looping!with indices', 'replace'=>'ciclo!con indici'];
$replace[]=['find'=>'looping!with strings', 'replace'=>'ciclo!con stringhe'];
$replace[]=['find'=>'math function', 'replace'=>'funzione matematica'];
$replace[]=['find'=>'membership!dictionary', 'replace'=>'membership!dictionary'];
$replace[]=['find'=>'membership!list', 'replace'=>'membership!list'];
$replace[]=['find'=>'membership!set', 'replace'=>'membership!set'];
$replace[]=['find'=>'memoria principale', 'replace'=>'memoria principale'];
$replace[]=['find'=>'memoria secondaria', 'replace'=>'memoria secondaria'];
$replace[]=['find'=>'message', 'replace'=>'messaggio'];
$replace[]=['find'=>'method', 'replace'=>'metodo'];
$replace[]=['find'=>'method!append', 'replace'=>'metodo!append'];
$replace[]=['find'=>'method!close', 'replace'=>'metodo!close'];
$replace[]=['find'=>'method!count', 'replace'=>'metodo!count'];
$replace[]=['find'=>'method!extend', 'replace'=>'metodo!extend'];
$replace[]=['find'=>'method!get', 'replace'=>'metodo!get'];
$replace[]=['find'=>'method!items', 'replace'=>'metodo!item'];
$replace[]=['find'=>'method!join', 'replace'=>'metodo!join'];
$replace[]=['find'=>'method!keys', 'replace'=>'metodo!chiavi'];
$replace[]=['find'=>'method!pop', 'replace'=>'metodo!pop'];
$replace[]=['find'=>'method!remove', 'replace'=>'metodo!remove'];
$replace[]=['find'=>'method!sort', 'replace'=>'metodo!sort'];
$replace[]=['find'=>'method!split', 'replace'=>'metodo!split'];
$replace[]=['find'=>'method!string', 'replace'=>'metodo!stringa'];
$replace[]=['find'=>'method!values', 'replace'=>'metodo!valori'];
$replace[]=['find'=>'method!void', 'replace'=>'metodo!nullo'];
$replace[]=['find'=>'method, list', 'replace'=>'metodo!list'];
$replace[]=['find'=>'methodsort', 'replace'=>'metodo!sort'];
$replace[]=['find'=>'mnemonic', 'replace'=>'mnemonico'];
$replace[]=['find'=>'modalità interattiva', 'replace'=>'modalità interattiva'];
$replace[]=['find'=>'module', 'replace'=>'modulo'];
$replace[]=['find'=>'module object', 'replace'=>'oggetto modulo'];
$replace[]=['find'=>'module!random', 'replace'=>'modulo!casuale'];
$replace[]=['find'=>'module!sqlite3', 'replace'=>'modulo!sqlite3'];
$replace[]=['find'=>'modulus operator', 'replace'=>'operatore modulo'];
$replace[]=['find'=>'mutability', 'replace'=>'mutabilità'];
$replace[]=['find'=>'negative index', 'replace'=>'indice negativo'];
$replace[]=['find'=>'nested conditional', 'replace'=>'condizione annidata'];
$replace[]=['find'=>'nested list', 'replace'=>'lista annidata'];
$replace[]=['find'=>'nested loops', 'replace'=>'cicli annidati'];
$replace[]=['find'=>'newline', 'replace'=>'a capo'];
$replace[]=['find'=>'non-greedy', 'replace'=>'non avido'];
$replace[]=['find'=>'normalization', 'replace'=>'normalizzazione'];
$replace[]=['find'=>'not operator', 'replace'=>'operatore not'];
$replace[]=['find'=>'number, random', 'replace'=>'numero, casuale'];
$replace[]=['find'=>'object', 'replace'=>'oggetto'];
$replace[]=['find'=>'object lifecycle', 'replace'=>'ciclo di vita dell\'oggetto'];
$replace[]=['find'=>'object!function', 'replace'=>'oggetto!funzione'];
$replace[]=['find'=>'object-oriented', 'replace'=>'ad oggetti'];
$replace[]=['find'=>'open function', 'replace'=>'funziona aperta'];
$replace[]=['find'=>'operand', 'replace'=>'operando'];
$replace[]=['find'=>'operator', 'replace'=>'operatore'];
$replace[]=['find'=>'operator!and', 'replace'=>'operatore!and'];
$replace[]=['find'=>'operator!boolean', 'replace'=>'operatore!booleano'];
$replace[]=['find'=>'operator!bracket', 'replace'=>'operatore!parentesi'];
$replace[]=['find'=>'operator!comparison', 'replace'=>'operatore!comparazione'];
$replace[]=['find'=>'operator!del', 'replace'=>'operatore!del'];
$replace[]=['find'=>'operator!format', 'replace'=>'operatore!formato'];
$replace[]=['find'=>'operator!in', 'replace'=>'operatore!in'];
$replace[]=['find'=>'operator!is', 'replace'=>'operatore!is'];
$replace[]=['find'=>'operator!logical', 'replace'=>'operatore!logico'];
$replace[]=['find'=>'operator!modulus', 'replace'=>'operatore!modulo'];
$replace[]=['find'=>'operator!not', 'replace'=>'operatore!not'];
$replace[]=['find'=>'operator!or', 'replace'=>'operatore!or'];
$replace[]=['find'=>'operator!slice', 'replace'=>'operatore!slice'];
$replace[]=['find'=>'operator!string', 'replace'=>'operatore!stringa'];
$replace[]=['find'=>'operator, arithmetic', 'replace'=>'operatore aritmetico'];
$replace[]=['find'=>'optional argument', 'replace'=>'argomento opzionale'];
$replace[]=['find'=>'or operator', 'replace'=>'operatore OR'];
$replace[]=['find'=>'order of operations', 'replace'=>'ordine delle operazioni'];
$replace[]=['find'=>'parameter', 'replace'=>'parametro'];
$replace[]=['find'=>'parent class', 'replace'=>'classe genitore'];
$replace[]=['find'=>'parentheses!argument in', 'replace'=>'parentesi!argomento in'];
$replace[]=['find'=>'parentheses!empty', 'replace'=>'parentesi!vuoto'];
$replace[]=['find'=>'parentheses!overriding precedence', 'replace'=>'parentesi!sovrascrittura della precedenza'];
$replace[]=['find'=>'parentheses!parameters in', 'replace'=>'parentesi!parametri in'];
$replace[]=['find'=>'parentheses!regular expression', 'replace'=>'parentesi!espressioni regolari'];
$replace[]=['find'=>'parentheses!tuples in', 'replace'=>'parentesi!tuple in'];
$replace[]=['find'=>'parsing HTML', 'replace'=>'parsing!HTML'];
$replace[]=['find'=>'parsing!HTML', 'replace'=>'parsing!HTML'];
$replace[]=['find'=>'pass statement', 'replace'=>'istruzione pass'];
$replace[]=['find'=>'pattern!DSU', 'replace'=>'pattern!DSU'];
$replace[]=['find'=>'pattern!decorate-sort-undecorate', 'replace'=>'pattern!decorate-sort-undecorate'];
$replace[]=['find'=>'pattern!filter', 'replace'=>'pattern!filter'];
$replace[]=['find'=>'pattern!guardian', 'replace'=>'pattern!guardian'];
$replace[]=['find'=>'pattern!search', 'replace'=>'pattern!search'];
$replace[]=['find'=>'pattern!swap', 'replace'=>'pattern!swap'];
$replace[]=['find'=>'persistence', 'replace'=>'persistenza'];
$replace[]=['find'=>'pi', 'replace'=>'pi greco'];
$replace[]=['find'=>'pop method', 'replace'=>'metodo pop'];
$replace[]=['find'=>'port', 'replace'=>'porta'];
$replace[]=['find'=>'portabilità', 'replace'=>'portabilità'];
$replace[]=['find'=>'precedence', 'replace'=>'precedenza'];
$replace[]=['find'=>'primary key', 'replace'=>'chiave primaria'];
$replace[]=['find'=>'problem solving', 'replace'=>'problem solving'];
$replace[]=['find'=>'programma', 'replace'=>'programma'];
$replace[]=['find'=>'prompt', 'replace'=>'prompt'];
$replace[]=['find'=>'pseudorandom', 'replace'=>'pseudorandom'];
$replace[]=['find'=>'quotation mark', 'replace'=>'virgolette'];
$replace[]=['find'=>'radian', 'replace'=>'radianti'];
$replace[]=['find'=>'randint function', 'replace'=>'funzione randint'];
$replace[]=['find'=>'random function', 'replace'=>'funzione random'];
$replace[]=['find'=>'random module', 'replace'=>'modulo random'];
$replace[]=['find'=>'random number', 'replace'=>'numero, casuale'];
$replace[]=['find'=>'random walk programming', 'replace'=>'random walk programming'];
$replace[]=['find'=>'rate limiting', 'replace'=>'limitazione del flusso'];
$replace[]=['find'=>'re module', 'replace'=>'modulo re'];
$replace[]=['find'=>'reference', 'replace'=>'riferimento'];
$replace[]=['find'=>'reference!aliasing', 'replace'=>'riferimento!aliasing'];
$replace[]=['find'=>'regex', 'replace'=>'regex'];
$replace[]=['find'=>'regex!character sets(brackets)', 'replace'=>'regex!insiemi di caratteri (parentesi)'];
$replace[]=['find'=>'regex!findall', 'replace'=>'regex!findall'];
$replace[]=['find'=>'regex!parentheses', 'replace'=>'regex!parentesi'];
$replace[]=['find'=>'regex!search', 'replace'=>'regex!search'];
$replace[]=['find'=>'regex!wild card', 'replace'=>'regex!wild card'];
$replace[]=['find'=>'regular expressions', 'replace'=>'espressioni regolari'];
$replace[]=['find'=>'relation', 'replace'=>'relazione'];
$replace[]=['find'=>'remove method', 'replace'=>'metodo remove'];
$replace[]=['find'=>'repetition!list', 'replace'=>'ripetizione!lista'];
$replace[]=['find'=>'repr function', 'replace'=>'funzione repr'];
$replace[]=['find'=>'return value', 'replace'=>'valore di ritorno'];
$replace[]=['find'=>'reversed function', 'replace'=>'funzione inversa'];
$replace[]=['find'=>'risoluzione dei problemi', 'replace'=>'risoluzione dei problemi'];
$replace[]=['find'=>'rules of precedence', 'replace'=>'regola della predenza'];
$replace[]=['find'=>'runtime error', 'replace'=>'runtime error'];
$replace[]=['find'=>'sanity check', 'replace'=>'controllo della sanità'];
$replace[]=['find'=>'scaffolding', 'replace'=>'impalcatura'];
$replace[]=['find'=>'scatter', 'replace'=>'scatter'];
$replace[]=['find'=>'scrape', 'replace'=>'scrape'];
$replace[]=['find'=>'script', 'replace'=>'script'];
$replace[]=['find'=>'script mode', 'replace'=>'modalità script'];
$replace[]=['find'=>'search pattern', 'replace'=>'modello di ricerca'];
$replace[]=['find'=>'secondary memory', 'replace'=>'memoria secondaria'];
$replace[]=['find'=>'semantic error', 'replace'=>'errore semantico'];
$replace[]=['find'=>'semantica', 'replace'=>'semantica'];
$replace[]=['find'=>'sequence', 'replace'=>'sequenza'];
$replace[]=['find'=>'set membership', 'replace'=>'set membership'];
$replace[]=['find'=>'shape', 'replace'=>'forma'];
$replace[]=['find'=>'shape error', 'replace'=>'errore di forma'];
$replace[]=['find'=>'short circuit', 'replace'=>'corto circuito'];
$replace[]=['find'=>'sine function', 'replace'=>'funzione sine'];
$replace[]=['find'=>'singleton', 'replace'=>'singleton'];
$replace[]=['find'=>'slice', 'replace'=>'tagliare'];
$replace[]=['find'=>'slice operator', 'replace'=>'operatore slice'];
$replace[]=['find'=>'slice!copy', 'replace'=>'tagliare!copy'];
$replace[]=['find'=>'slice!list', 'replace'=>'tagliare!list'];
$replace[]=['find'=>'slice!string', 'replace'=>'tagliare!stringa'];
$replace[]=['find'=>'slice!tuple', 'replace'=>'tagliare!tupla'];
$replace[]=['find'=>'slice!update', 'replace'=>'tagliare!aggiornamento'];
$replace[]=['find'=>'socket', 'replace'=>'socket'];
$replace[]=['find'=>'sort method', 'replace'=>'metodo sort'];
$replace[]=['find'=>'sort method!', 'replace'=>'metodo sort'];
$replace[]=['find'=>'sorted function', 'replace'=>'funzione ordinamento'];
$replace[]=['find'=>'special value!False', 'replace'=>'valore speciale!False'];
$replace[]=['find'=>'special value!None', 'replace'=>'valore speciale!None'];
$replace[]=['find'=>'special value!None', 'replace'=>'valore speciale!None'];
$replace[]=['find'=>'spider', 'replace'=>'spider'];
$replace[]=['find'=>'split method', 'replace'=>'metodo split'];
$replace[]=['find'=>'sqlite3 module', 'replace'=>'modulo sqlite3'];
$replace[]=['find'=>'sqrt function', 'replace'=>'funzione!sqrt'];
$replace[]=['find'=>'squiggly bracket', 'replace'=>'parentesi ondulata'];
$replace[]=['find'=>'statement', 'replace'=>'istruzione'];
$replace[]=['find'=>'statement!assignment', 'replace'=>'istruzione!assegnazione'];
$replace[]=['find'=>'statement!break', 'replace'=>'break'];
$replace[]=['find'=>'statement!compound', 'replace'=>'istruzione!composta'];
$replace[]=['find'=>'statement!conditional', 'replace'=>'istruzione!condizionale'];
$replace[]=['find'=>'statement!continue', 'replace'=>'istruzione!continue'];
$replace[]=['find'=>'statement!for', 'replace'=>'istruzione!for'];
$replace[]=['find'=>'statement!if', 'replace'=>'istruzione!if'];
$replace[]=['find'=>'statement!import', 'replace'=>'istruzione!import'];
$replace[]=['find'=>'statement!pass', 'replace'=>'istruzione!pass'];
$replace[]=['find'=>'statement!try', 'replace'=>'istruzione!try'];
$replace[]=['find'=>'statement!while', 'replace'=>'istruzione!while'];
$replace[]=['find'=>'str function', 'replace'=>'funzione str'];
$replace[]=['find'=>'string', 'replace'=>'stringa'];
$replace[]=['find'=>'string method', 'replace'=>'metodo string'];
$replace[]=['find'=>'string representation', 'replace'=>'rappresentazione stringa'];
$replace[]=['find'=>'string type', 'replace'=>'tipo stringa'];
$replace[]=['find'=>'string!comparison', 'replace'=>'stringa!comparazione'];
$replace[]=['find'=>'string!empty', 'replace'=>'stringa!vuota'];
$replace[]=['find'=>'string!find', 'replace'=>'stringa!trova'];
$replace[]=['find'=>'string!immutable', 'replace'=>'stringa!immutabile'];
$replace[]=['find'=>'string!method', 'replace'=>'stringa!metodo'];
$replace[]=['find'=>'string!operation', 'replace'=>'stringa!operazione'];
$replace[]=['find'=>'string!slice', 'replace'=>'string!slice'];
$replace[]=['find'=>'string!split', 'replace'=>'string!split'];
$replace[]=['find'=>'string!startswith', 'replace'=>'stringa!iniziacon'];
$replace[]=['find'=>'swap pattern', 'replace'=>'swap pattern'];
$replace[]=['find'=>'syntax error', 'replace'=>'syntax error'];
$replace[]=['find'=>'temperature conversion', 'replace'=>'conversione della temperatura'];
$replace[]=['find'=>'text file', 'replace'=>'file di testo'];
$replace[]=['find'=>'time', 'replace'=>'time'];
$replace[]=['find'=>'time.sleep', 'replace'=>'time.sleep'];
$replace[]=['find'=>'traceback', 'replace'=>'traceback'];
$replace[]=['find'=>'traversal', 'replace'=>'traversal'];
$replace[]=['find'=>'traversal!list', 'replace'=>'traversal!list'];
$replace[]=['find'=>'traverse!dictionary', 'replace'=>'traverse!dictionary'];
$replace[]=['find'=>'trigonometric function', 'replace'=>'funzione trigonometrica'];
$replace[]=['find'=>'try statement', 'replace'=>'istruzione try'];
$replace[]=['find'=>'tuple', 'replace'=>'tupla'];
$replace[]=['find'=>'tuple assignment', 'replace'=>'assegnazione tuple'];
$replace[]=['find'=>'tuple function', 'replace'=>'funzione tupla'];
$replace[]=['find'=>'tuple!as key in dictionary', 'replace'=>'tuple!come chiave in un dizionario'];
$replace[]=['find'=>'tuple!assignment', 'replace'=>'tuple!assegnamento'];
$replace[]=['find'=>'tuple!comparison', 'replace'=>'tuple!comparazione'];
$replace[]=['find'=>'tuple!in brackets', 'replace'=>'tuple!in brackets'];
$replace[]=['find'=>'tuple!singleton', 'replace'=>'tuple!singleton'];
$replace[]=['find'=>'tuple!slice', 'replace'=>'tuple!slice'];
$replace[]=['find'=>'type', 'replace'=>'tipo'];
$replace[]=['find'=>'type conversion', 'replace'=>'conversione tra tipi'];
$replace[]=['find'=>'type!bool', 'replace'=>'tipo!bool'];
$replace[]=['find'=>'type!dict', 'replace'=>'tipo!dict'];
$replace[]=['find'=>'type!file', 'replace'=>'tipo!file'];
$replace[]=['find'=>'type!list', 'replace'=>'tipo!elenco'];
$replace[]=['find'=>'type!tuple', 'replace'=>'tipo!tupla'];
$replace[]=['find'=>'typographical error', 'replace'=>'errore tipografico'];
$replace[]=['find'=>'underscore character', 'replace'=>'carattere underscore'];
$replace[]=['find'=>'update', 'replace'=>'aggiorna'];
$replace[]=['find'=>'update!item', 'replace'=>'update!item'];
$replace[]=['find'=>'update!slice', 'replace'=>'update!slice'];
$replace[]=['find'=>'urllib!image', 'replace'=>'urllib!immagine'];
$replace[]=['find'=>'use before def', 'replace'=>'uso prima di def'];
$replace[]=['find'=>'value', 'replace'=>'valore'];
$replace[]=['find'=>'values method', 'replace'=>'metodo values'];
$replace[]=['find'=>'variable', 'replace'=>'variabile'];
$replace[]=['find'=>'variable!updating', 'replace'=>'variabile!aggiornamento'];
$replace[]=['find'=>'void function', 'replace'=>'funzione void'];
$replace[]=['find'=>'void method', 'replace'=>'metodo void'];
$replace[]=['find'=>'web service', 'replace'=>'servizio web'];
$replace[]=['find'=>'web!scraping', 'replace'=>'web!scraping'];
$replace[]=['find'=>'while loop', 'replace'=>'ciclo while'];
$replace[]=['find'=>'whitespace', 'replace'=>'spazio'];
$replace[]=['find'=>'wild card', 'replace'=>'carattere jolly'];
$replace[]=['find'=>'zero, index starting at', 'replace'=>'zero, partenza dell\'indice da'];
